CORE ?= esp32
BOARD ?= ttgo-t7-v14-mini32

UPLOADSPEED := 921600
SERIAL_PORT ?= /dev/ttyACM0
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
#CPPFLAGS := -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DDEBUGGING=0x20
CPPFLAGS := -DTERMINAL_SPEED=$(TERMINAL_SPEED)
LIBRARIES = SimpleTimer

include $(CORE).mk
