CORE ?= esp32
BOARD ?= ttgo-t7-v14-mini32

UPLOADSPEED := 921600
SERIAL_PORT ?= /dev/ttyACM0
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
CPPFLAGS := -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DSIMPLE_TIMER_MICROS -DNO_STORAGE -DUSE_HOST_DISPLAY -DUSE_HOST_KBD
#CPPFLAGS += -DDEBUGGING=0x19
LIBRARIES = SimpleTimer

include $(CORE).mk
